stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: python -V
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 192.168.1.251:7003/qa/demo:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: 192.168.1.251:7003
timeout: 60
notification: {}
