stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: python -V
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 192.168.1.251:7003/qa/demo:${CICD_GIT_COMMIT}
      registry: 127.0.0.1:34201
timeout: 60
notification: {}
